# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-06 18:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=50)),
                ('terms_passed', models.PositiveSmallIntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=7)),
                ('course_name', models.CharField(max_length=50)),
                ('course_credits', models.FloatField()),
                ('course_grade', models.FloatField(choices=[(4.0, 'AA'), (3.5, 'BA'), (3.0, 'BB'), (2.5, 'CB'), (2.0, 'CC'), (1.5, 'DC'), (1.0, 'DD'), (0.0, 'FF')])),
                ('course_comments', models.TextField()),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('semester', models.CharField(max_length=15)),
                ('total_credit', models.FloatField()),
                ('given_credit', models.FloatField()),
                ('average', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Term'),
        ),
    ]
